#include "header.h"


/**
 * Test\Router\Exception
 *
 * Exceptions generated by the router
 */
ZEPHIR_INIT_CLASS(Test_Router_Exception) {

	ZEPHIR_REGISTER_CLASS_EX(Test\\Router, Exception, test, router_exception, zend_exception_get_default(TSRMLS_C), NULL, 0);


	return SUCCESS;

}

